language: python

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"
    - "$HOME/.cache/pre-commit"

stages:
  - linting
  - test

before_install:
  # linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install swig3.0; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo ln -s /usr/bin/swig3.0 /usr/bin/swig; fi
  - pip install poetry
install:
  - poetry install -v
  - poetry run pip install tox tox-travis coveralls
script:
  - poetry run tox
after_success:
  - poetry run coveralls

jobs:
  include:
    - python: "3.5"
    - python: "3.6"

    - stage: linting
      python: "3.6"
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files